{
  if (getCause() instanceof Exception) {
    throw (Exception)getCause();
  }
  throw this;
}
